name: Publish GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build font
        run: npm run build

  publish:
      runs-on: ubuntu-latest

      steps:
        - name: Push to gh-pages branch
          run: | # Don't ignore the dist folder except the .ttf
            rm .gitignore
            git add dist/codicon.csv
            git add dist/codicon.css
            git add dist/codicon.html
            git add dist/codicon.svg
            git commit -m "gh-pages: Update website"
            git push origin gh-pages
