name: Codicons Build

on:
  push:
    branches: [ main ]
    tags:        
      - '*' # Only runs on annotated tags
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build font
        run: npm run build

      - name: Upload codicon.ttf as artifact
        uses: actions/upload-artifact@v4
        with:
          name: codicon-font-${{ github.sha }}.ttf
          path: dist/codicon.ttf

      - name: PR to microsoft/vscode
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH="update-codicons"
          MESSAGE="chore: Update codicons to ${{ github.sha }}"
          USER_NAME="GitHub Actions at microsoft/vscode-codicons"
          USER_EMAIL="hylbo@microsoft.com"

          git clone --depth=1 https://github.com/microsoft/vscode.git
          cd vscode
          git checkout -b $BRANCH

          cp ../dist/codicon.ttf src/vs/base/browser/ui/codicons/codicon/
          cp ../dist/codiconsLibrary.ts src/vs/base/common/

          git add .
          git config --global user.name "$USER_NAME"
          git config --global user.email "$USER_EMAIL"
          git commit -m "$MESSAGE"

#          git push -f origin $BRANCH

#          echo "${{ secrets.ACCESS_TOKEN }}" > token.txt
#          gh auth login --with-token < token.txt

#          gh pr create \
#            --title "$MESSAGE" \
#            --body "" \
#            --base "main" \
#            --head "$BRANCH"


  # Create a release when a new tag is pushed
  publish:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # All history

      - name: Write release notes
        if: startsWith(github.ref, 'refs/tags/')
        run: | # List all commits since last tag
          commits=$(git log --pretty=format:"* %s (%h)" $(git describe --abbrev=0 --tags `git rev-list --tags --skip=1  --max-count=1`)...)
          echo -e "This release includes:\n${commits}" > release_notes.txt

          {
            echo 'release_notes<<EOF'
            cat release_notes.txt
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Create Release 
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
          body: ${{ env.release_notes }}

      - name: Install dependencies
        run: npm install

      - name: Build font
        run: npm run build

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: dist/codicon.ttf
          asset_name: codicon-font-${{ github.ref_name }}.ttf
